name: Build Check
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Use custom NuGet build check action
        uses: Official-EwE/Eii.GithubActions/BuildCheckNet80@master    # can also be BuildCheckNet48Net80@v.. etcc
